### ISSUE TITLE
Please destroy this repository and everything in it

### ISSUE THREAD

**Issue by Ironholds** [scoliann/TinderFaceScraper#4]
Surfacing otherwise-assumed-closed data around dating, relationships and preferences into the public domain is exceedingly inappropriate. As the [OKCupid saga](https://www.wired.com/2016/05/okcupid-study-reveals-perils-big-data-science/) taught any researcher following conversations around research ethics or online platforms, these datasets tend to contain personally identifiable information that can be used to track or harm a lot of people, many of them marginalised.

While you have now removed the dataset - only, I note, because Kaggle required it, not because you twigged to the ethical and moral problems with it - you have not removed the code, making it relatively simple for anyone to take your work and do precisely the same thing again. I urge you, if you are genuinely interested in using data science to improve the world, to delete this dataset *and code*. Nothing good can come of it.

**Comment by yeralin** [comment]
for hoe in hoes: ? Screw that. It is not open source :/

**Comment by Ironholds** [comment]
The FOSS status is your problem?

**Comment by kvzivn** [comment]
i loled at `hoes` too

**Comment by Ironholds** [comment]
Oh good, now we're up to three people I'll make a note to never hire

**Comment by wintermute0001** [comment]
@Ironholds  glad someone here isn't disgusting. 

seriously, `hoes`? wtf is wrong with you.

**Comment by cornfeedhobo** [comment]
@scoliann I really hope this ruins your career. This is extremely unethical.

**Comment by cdepeuter** [comment]
Not sure whats more absurd, the variable name "hoes" and putting that up publicly not realizing how absurd and offensive it is, or the commit describing the change clearly.

https://github.com/scoliann/TinderFaceScraper/commit/841ed225a7fca185d249f0bbbcc5382fd9bfcb49

**Comment by BradChism** [comment]
Honestly, this is interesting. But let me explain. and oh before I continue, for the record, I don't care if people don't want to hire me. that isn't what this is about. 

So on one hand, you have a program that can destroy lives in seconds, variables that reference hoe/hoes which is a tool, you can classify it for what you want, but lets clear that up that the name is a tool which is exactly what this program is. You have a program that does not just seek ladies, it seeks men too so if a Man is classified as a hoe, then obviously you shouldn't be looking for programmers anyways. 

But now lets flip the switch and you have a tool that can help find people, police stations, regular people on the streets looking for a missing person can now take a working code and find a missing person or a picture of a missing person and help their case in finding someone that might have ended up in a sex traffic ring or ended up on some pimps work sheet, or worse dead because someone didn't take the time to look deeper using such a program that could help excel their results in finding a person if the missing person had pictures taken before their death or other events that will link back to who did what to the missing person. 

With some more modifications to the code you can narrow it down and help society, I hope this code stays but maybe implement some encryption of the base extraction code or a token to make sure it gets used correctly. 

In any case, if you want to use the program to be a pervert or stalker then that is your karma as there are other tools to find you, if that is where your mind is. However I can see this being a very helpful tool in the right hands. 

Be well and good luck out there. 
Appreciate the time you took to make it and I hope you can put it to good use, I'd market it to the authorities as a person finder tool if I was the primary programmer. 

Brad

**Comment by YouShouldBeShamed1** [comment]
I see a post here has been deleted. So you post everyone else's private data, but you can't have yours exposed?

Please forward all complaints to PG&E so they can know better what type of person they are employing. I am certain his department will appreciate the attention.
http://www.pgecorp.com/aboutus/ethics_compliance/con_con_ven/index.shtml

**Comment by YouShouldBeShamed1** [comment]
Please forward all complaints to PG&E so they can know better what type of person they are employing.
I am certain his [boss (https://twitter.com/berniecowens)](https://twitter.com/berniecowens) will appreciate the attention.

P.S. I made a script to automate the creation of these accounts and of this post. Feel free to flag ;-)

**Comment by YouShouldBeShamed2** [comment]
Please forward all complaints to PG&E so they can know better what type of person they are employing.
I am certain his boss (https://twitter.com/berniecowens) will appreciate the attention.

P.S. I made a script to automate the creation of these accounts and of this post. Feel free to flag ;-)

**Comment by YouShouldBeShamed3** [comment]
Please forward all complaints to PG&E so they can know better what type of person they are employing.
I am certain his [boss (https://twitter.com/berniecowens)](https://twitter.com/berniecowens) will appreciate the attention.

P.S. I made a script to automate the creation of these accounts and of this post. Feel free to flag ;-)

**Comment by Ironholds** [comment]
Mr Chism,

Let me give some background and a further explanation. I am a human-computer interaction researcher. I've been based in this field for five years, starting off with Wikimedia where I was the general privacy/data dork and maintained most of their readership data (including, yes, what people viewed). I was also one of the people who broke the OKCupid leak this-ish time last year (evidently March is just silly season for some people). I currently work in a machine learning job in information aecurity, and am shortly to start my PhD. In other words, it is fairly safe to say that I am less-than-ignorant about issues around the intersect of machine learning, data ethics, and human factors in computing.

Your argument does not actually address the code itself at all, nor the issues with it. To begin, that it might be misused is far from the only problem; the greater issues are:

1. It was gathered illegally
2. It was gathered without any kind of consent of the subjects
3. It is intended for an inherently transphobic and erasing research project.

A list of ideas of useful things it could be used for is sort of irrelevant, because none of them are anywhere near the intended use; it's literally just intended as a genderiser, and a poor one at that which will inevitably misclassify trans and non/binary people while reinforcing the false binary - in doing so, causing not-insignificant harm. That's before we get anywhere near the other obvious risk factors ("Wife dearest, why is your photo on tinder?").

Moreover, I'm bemused by your actual proposals. Building tools for 'the authorities' is, again, approximately fifty astronomic units away from what the code actually does or intends to do, and is nowhere near an inherent moral good or politically neutral act. In the event this was, in fact, a face-matching app (and it is not) "person finders" can be used for missing persons, yes, or criminals, yes, or state suppression of dissidents, or drone bombings, or, or, or, or. It is not a morally neutral field to be working in, something that I imagine the original author is learning *quite* rapidly.

**Comment by ypnos** [comment]
You are arguing about the data here, and about the author of the code, and throwing a bunch of libelous assumptions into the mix there, too.

But did you actually have a look at the code at hands? It is so damn simple, really anyone with any bad intentions and a bit of dedication can get to it. And it is actually based on another project:
https://github.com/jaungiers/Tinder-py_auto_liker/blob/master/tinder-py_auto_liker.py

As you can see, the contribution of the author is quite small. Now instead of complaining about childish (and copied-over) variable names and calling a naïve/outdated world view transphobic, maybe you should look at the more grave concerns here. As, in fact, you seem to be very concerned about user privacy, and rightfully so!

- It only takes a few lines of code to extract thousands of user images from Tinder
- Furthermore, Tinder provide an API to do exactly that by themselves
- Obviously, it was not only easy to write the script, but also to collect such a mass of data

As you might realize, the problem really starts at Tinder. A service, I might add, that has ToC which enable Tinder themselves to do whatever they want with this image data. Legally. I think this is a far bigger issue than a silly pet 'research' project. I for one congratulate the author, who from my point of view only acted in good faith (yet did the wrong thing with publishing the data, but _not_ with publishing the code), for raising a greater awareness to this issue. Which affects our society as a whole.

**Comment by Ironholds** [comment]
Where are the libelous assumptions? And no, I called the *project* transphobic and erasing, because that's what it is.

Yes, I've read the code, and yes, I am aware it is tremendously simple, and yes, I am aware that this is part of a wider industry problem. I spent my morning [telling Forbes precisely that](https://www.forbes.com/sites/janetwburns/2017/05/02/tinder-profiles-have-been-looted-again-this-time-for-teaching-ai-to-genderize-faces/). But applauding the author for 'raising a greater awareness' is both facile  - we already knew about these kinds of problems, there have been multiple breaches through this API, there have been multiple dating site breaches, I reported on the last ones, too - and completely irrelevant to the problem that if he genuinely understands the problem this code should not be live, nor should any evidence the project ever existed except for a short note explaining it was a bad idea. 

I appreciate the actual repo holder has yet to chip in here. On the off-chance he's reading it; please, just get rid of your code. Delete the repo, create a new one with a README of "this was a bad idea, here is why, here is how I have gone about nixing the data and code in its entirety". Your biography says "Always trying to improve" - well, the last few days have been full of kind of a lot of pointers on that. Please?

Either way I'm just going to stop replying to this thread - I'm finding the responses (particularly the one above) kind of irritating and patronising in the assumptions that they make about my background and knowledge, and I have better things to do.

**Comment by ypnos** [comment]
What I am referring to is the news coverage this issue is getting. Not your or my personal awareness. I mean, Forbes is covering it, as you pointed out, among many other media outlets. Hiding this proof-of-concept code from the public on the other hand, does not make the 'bad guys' suddenly stop taking advantage of the Tinder API or the gullibility of the general public.

And btw., I didn't see anybody making any assumptions about your person, but from your choice of words I do start to assume a few things about you. Guess what, being contacted by media that found your text here, your 'long-term' five years 'background', or being about to start a PhD doesn't give you any special authority in this subject. The only person patronizing here were you.

**Comment by h-2-0** [comment]
https://pastebin.com/PCKqPqmX

**Comment by JohnSmith20018** [comment]
@Ironholds 

> it's literally just intended as a genderiser, and a poor one at that which will inevitably misclassify trans and non/binary people while reinforcing the false binary - in doing so, causing not-insignificant harm. 

I have trouble believing that you aren't just trolling with your comments. A classifier that tries to distinguish between female and male faces using biological and social elements is not "transphobic" or even wrong in any sense. It's not going to be used in a setting where anything other than the two different options are needed. And, the simplicity of this means many people just starting out with machine learning (both male, and female, and everything in between) are going to make simple classifiers for things like gender, faces, etc...

**Comment by Ironholds** [comment]
It's absolutely wrong because gender *and sex* are not binaries and because "gender as bio/hormonal/social cues" has been done, and is tremendously inaccurate due to the wide range of gender presentations.

And yes, many people are going to start out doing incorrect things: that's why we correct them. For example, one might start off engaging in data retrieval and machine learning projects without thinking about the wider sociopolitical impact of your work, or the ethics of the data retrieval, or the assumptions your research is based on, and then get corrected and not make that mistake again.

**Comment by lucaswxp** [comment]
Where is the freedom of speech!!? You can't even name your variables the way you want it to? I see it as a joke, taking into account the intent of the app!

My point is, stop being a pussy about it.

**Comment by wintermute0001** [comment]
@lucaswxp why are you so triggered by how we hate sexism and other such things? stop being such a snowflake.

**Comment by lucaswxp** [comment]
@wintermute0001 Oh man, don't you get it you can't be offended on behalf of others? I would like to see a person who had TRULY being damaged by this script, then I'd agree with you. But it's not the case and never will be.

**Comment by wintermute0001** [comment]
you're the one upset. stop being such a snowflake.  people don't like sexism. get over it.

**Comment by lucaswxp** [comment]
@wintermute0001 You are the one wanting to take this repository down because of a variable named "hoe" and I'm the snowflake? That's funny, please write more :D

**Comment by theapache64** [comment]
Guys (except Ironholds :/ ),

 when i run 'python3 tinderGetPhotos.py' , i get  

'Traceback (most recent call last):
  File "tinderGetPhotos.py", line 8, in <module>
    import selenium
ImportError: No module named 'selenium''

I've set facebook_token, facebook_id and imagePath. What am i missing ? I am on Ubuntu 16.04 . Please help :) 
(I don't knw python)

**Comment by tollymain** [comment]
delete this

**Comment by theapache64** [comment]
What can happen if @scoliann doesn't ? 
- Asking just out of curiosity :/  @tollymain

**Comment by theapache64** [comment]
:dancer:
