### ISSUE TITLE
KeyError: 'results' 

### ISSUE THREAD

**Issue by MDAWebDev** [scoliann/TinderFaceScraper#8]
![scrapererror](https://cloud.githubusercontent.com/assets/10343964/25594905/9d8366e4-2e90-11e7-9315-10552da301d5.PNG)

I keep getting this error when I try to run your scraper. It looks like it might be failing to get the Tinder API's x_auth_token. I'm not sure if this is a result of Tinder cracking down on the API or if I'm just doing something wrong.

**Comment by scoliann** [comment]
Hi MDAWebDev,

It does appear that something is breaking.  I think you're right, it could be a problem with the x_auth_token not being accepted.  One step that might help you debug this is to print the contents of `r2.json()` to terminal.  This will let you see what is being returned by Tinder when you request a batch of subjects.  I suspect you might be getting back some kind of error (which you could Google).

**Comment by pipiscrew** [comment]
same here, printing the 

> r2.json() 

> {'message': 'recs timeout'}

**Comment by fillupt** [comment]
<Response [400]>

**Comment by JohnSmith20018** [comment]
@fillupt @scoliann So how does one resolve `Response [200] `?

**Comment by JohnSmith20018** [comment]
I figured out the issue. It's related to Facebook accounts not meeting a certain criteria. Maybe something like age? Number of friends? Number of photos? Number of profile photos?

**Comment by JohnSmith20018** [comment]
@scoliann So I discovered the two causes of the issue. There is a bug that results in infinite searching for matching, which is somehow tied to an account. This bug affects both manual users and users using scripts, and of the fixes that I tried, the only one that worked was repeatedly deleting the account and making a new one until the bug was no longer affecting the account. The other cause of this issue, is as you said, that the potential matches in your area have been exhausted. This is fixed by waiting for half a day, to a few days for Tinder's algorithm to locate new potential matches.
